WeatherDashboard/WeatherDashboard/Controllers/Api/weatherbitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WeatherDashboard.Model;
using Newtonsoft.Json;

namespace WeatherDashboard.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/weatherbit")]
    public class WeatherbitController : Controller
    {
        [HttpGet]
        public JSONData GetJSONInfo(int cityId)
        {
            // Default value is Obregon.
            string cityName = GetCityById(cityId);

            // Build the Url
            var url = string.Format("{0}city={1}&country{2}&key={3}", WebApiConstant.URL, cityName
               , WebApiConstant.COUNTRY, WebApiConstant.KEY);

            using (WebClient webClient = new WebClient())
            {
                // Get our webApi Response.
                string JSONResponse = webClient.DownloadString(url);

                // Convert the Json string to a series of objects.
                var weatherCollection = JsonConvert.DeserializeObject<JSONData>(JSONResponse);

                return weatherCollection;
            }

        }

        private string GetCityById(int cityId)
        {
            var city = "";
            switch (cityId)
            {
                case 0:
                    city = "Cajeme";
                    break;

                case 1:
                    city = "Hermosillo";
                    break;

                case 2:
                    city = "Navojoa";
                    break;

                case 3:
                    city = "Nogales";
                    break;

                default:
                    city = "Cajeme";
                    break;

            }

            return city;
        }

    }
}

WeatherDashboard/WeatherDashboard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WeatherDashboard.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            ViewData["RequestId"] = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View();
        }
    }
}

WeatherDashboard/WeatherDashboard/Controllers/SampleDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WeatherDashboard.Controllers
{
    [Route("api/[controller]")]
    public class SampleDataController : Controller
    {
        private static string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        [HttpGet("[action]")]
        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                DateFormatted = DateTime.Now.AddDays(index).ToString("d"),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            });
        }

        public class WeatherForecast
        {
            public string DateFormatted { get; set; }
            public int TemperatureC { get; set; }
            public string Summary { get; set; }

            public int TemperatureF
            {
                get
                {
                    return 32 + (int)(TemperatureC / 0.5556);
                }
            }
        }
    }
}

WeatherDashboard/WeatherDashboard/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WeatherDashboard.Controllers.Api;
using WeatherDashboard.Model;


namespace WeatherDashboard.Controllers
{
    public class WeatherController : Controller
    {
        [HttpGet("[action]")]
        public IEnumerable<Weather> GetWeathers(int cityId)
        {

            var jSONData = new WeatherbitController();
            var forecast = jSONData.GetJSONInfo(cityId);

            return forecast.Data;

        }

        public ActionResult ForecastIndex(int cityId)
        {
            var getWeather = GetWeathers(cityId);

            return View("ForecastIndex", getWeather);
        }

        [HttpPost]
        public ActionResult OnChange(int cityId)
        {

            var getWeather = GetWeathers(cityId);

            return View("ForecastIndex", getWeather);
        }
    }
}

WeatherDashboard/WeatherDashboard/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>

<script src="~/dist/vendor.js" asp-append-version="true"></script>
@section scripts {
    <script src="~/dist/main-client.js" asp-append-version="true"></script>
}

WeatherDashboard/WeatherDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherDashboard</title>
    <base href="~/" />

    <link rel="stylesheet" href="~/dist/vendor.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

WeatherDashboard/WeatherDashboard/Views/Weather/ForecastIndex.cshtml
@model IEnumerable<WeatherDashboard.Model.Weather>

@{
    ViewData["Title"] = "ForecastIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Weather</h2>


@using (@Html.BeginForm("OnChange", "Weather"))
{
    var list = new List<SelectListItem>();
    var selected = new SelectListItem();
    list.Add(new SelectListItem() { Value = "0",Text="Cajeme"});
    list.Add(new SelectListItem() { Value = "1", Text = "Hermosillo" });
    list.Add(new SelectListItem() { Value = "2", Text = "Nogales" });
    list.Add(new SelectListItem() { Value = "3", Text = "Navojoa" });


    @Html.DropDownList("SortBy", list,  new { onchange = "form.submit()"});

}
<table class="table">
    <tr>
        <th>
            <p>Date</p>
        </th>
        <th>
            <p>Temperature</p>
        </th>
    </tr>

    @foreach (var weather in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => weather.Valid_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => weather.Temp)
            </td>

        </tr>
    }
</table>